#ifndef CAN_ID_H
#define CAN_ID_h

enum CanMessageID{
	CAN_ID_DEMANDE_NUM_CARTE = 0,
	CAN_ID_DEMANDE_ALIMENTATION = 1,
	CAN_ID_DEMANDE_HUMIDITE = 2,
	CAN_ID_DEMANDE_IRRADIANCE = 3,
	CAN_ID_DEMANDE_TEMP_EXTERIEUR = 4,
	CAN_ID_DEMANDE_HUM_IRR_TEMP_EXT = 5,
	CAN_ID_DEBUT_TRANSMITION = 7,
	CAN_ID_FIN_TRANSMISSION = 8,
	CAN_ID_RENVOI_NUM_CARTE = 10,
	CAN_ID_DEMANDE_MESURE_VI = 11,
	CAN_ID_DEMANDE_TEMP_PANNEAU = 12,
	CAN_ID_RENVOI_TEMP_PANNEAU = 18,
	CAN_ID_RENVOI_MESURE_VI = 19,
	CAN_ID_RENVOI_HUMIDITE = 42,
	CAN_ID_RENVOI_TEMPERATURE = 43,
	CAN_ID_RENVOI_IRRADIANCE = 44,
	CAN_ID_RENVOI_HUM_IRR_TEMP_EXT = 45,
	CAN_ID_DEMANDE_TENSION_STRING = 50,
	CAN_ID_DEMANDE_COURANT_STRING = 52,
	CAN_ID_RENVOI_COURANT_STRING = 	53,
	CAN_ID_RENVOI_TENSION_STRING = 51
};

#endif

